name: проверка PR в draft
on:
  pull_request:
    types: [opened, edited]
    branches:
      - draft-*
jobs:
  draft-merge:
    runs-on: ubuntu-latest
    steps:
      - name: main
        run: |

          TARGET="${{ github.base_ref }}"
          FROM="${{ github.head_ref }}"

          if [[ "$FROM" == ocode-* ]]; then
            echo "Слияние может быть одобрено"
            exit 0

          elif [[ "$FROM" != ocode-* ]]; then
            echo "Слияние запрещено. FROM != ocode"
            exit 1
          fi
